version: "latest"

services:
  api:
    # build: ./ToDo-API
    image: radwamohamed125/todo-api
    container_name: todo_api
    ports:
      - "3000:3000"
    networks:
      - todo-network

  frontend:
    # build: ./ToDo-Frontend
    image: radwamohamed125/todo-frontend
    container_name: todo_frontend
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
